[greeter]
background = /usr/share/backgrounds/wallpaper.png
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = MesloLGMDZ Nerd Font 10
xft-antialias = true
xft-hintstyle = slight
xft-rgba = rgb
indicators = ~clock;~power;~session
clock-format = %H:%M
position = 50%,50%
screensaver-timeout = 60
