# Catppuccin Latte
foreground #4c4f69
background #eff1f5

# Cursor
cursor #dc8a78
cursor_text_color #eff1f5

# Selection
selection_foreground #eff1f5
selection_background #7287fd

# Black
color0 #5c5f77
color8 #acb0be

# Red
color1 #d20f39
color9 #d20f39

# Green
color2 #40a02b
color10 #40a02b

# Yellow
color3 #df8e1d
color11 #df8e1d

# Blue
color4 #1e66f5
color12 #1e66f5

# Magenta
color5 #ea76cb
color13 #ea76cb

# Cyan
color6 #179299
color14 #179299

# White
color7 #acb0be
color15 #bcc0cc

# URLs
url_color #1e66f5

# Marks
mark1_foreground #eff1f5
mark1_background #1e66f5

# Tab bar
active_tab_foreground #eff1f5
active_tab_background #1e66f5
inactive_tab_foreground #6c6f85
inactive_tab_background #ccd0da

# Misc
dimmed_text_color #9ca0b0
bell_border_color #d20f39
