foreground #4c4f69
background #eff1f5

cursor #dc8a78
cursor_text_color #eff1f5

selection_foreground #eff1f5
selection_background #7287fd

color0 #5c5f77
color1 #d20f39
color2 #40a02b
color3 #df8e1d
color4 #1e66f5
color5 #ea76cb
color6 #179299
color7 #acb0be

color8 #acb0be
color9 #d20f39
color10 #40a02b
color11 #df8e1d
color12 #1e66f5
color13 #ea76cb
color14 #179299
color15 #bcc0cc

url_color #1e66f5

search_match_no_1 #df8e1d
search_match_no_2 #d20f39

active_tab_foreground #eff1f5
active_tab_background #1e66f5
inactive_tab_foreground #6c6f85
inactive_tab_background #ccd0da

inactive_border_color #ccd0da
active_border_color #1e66f5

bell_border_color #d20f39

dimmed_text_color #9ca0b0
